// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALqVZyDM222un2hkiCp0P3o8SZ_HbCxIk',
    appId: '1:33808997976:web:4dc9d31183b89cdc7cb42d',
    messagingSenderId: '33808997976',
    projectId: 'carpool-36d3f',
    authDomain: 'carpool-36d3f.firebaseapp.com',
    storageBucket: 'carpool-36d3f.appspot.com',
    measurementId: 'G-DWQECYJYF3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDBm0Nnj0zHxj2BqDI5ChonYi-ISb20L8',
    appId: '1:33808997976:android:86da455d0bedb03b7cb42d',
    messagingSenderId: '33808997976',
    projectId: 'carpool-36d3f',
    storageBucket: 'carpool-36d3f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAocViX3oEAw4Mk__kMr5I9qBVpczu__Ak',
    appId: '1:33808997976:ios:a2444127d3017f337cb42d',
    messagingSenderId: '33808997976',
    projectId: 'carpool-36d3f',
    storageBucket: 'carpool-36d3f.appspot.com',
    iosClientId: '33808997976-lhib05bijq2kl8hrb283f8fvp4pi3rn7.apps.googleusercontent.com',
    iosBundleId: 'com.example.carPool',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAocViX3oEAw4Mk__kMr5I9qBVpczu__Ak',
    appId: '1:33808997976:ios:0dc4b47fb4fa1a1e7cb42d',
    messagingSenderId: '33808997976',
    projectId: 'carpool-36d3f',
    storageBucket: 'carpool-36d3f.appspot.com',
    iosBundleId: 'com.example.carPool.RunnerTests',
  );
}
